---
name: build

defaults:
  run:
    shell: bash

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.14'
    - run: go version
    - run: go test ./...

  version:
    needs: test
    outputs:
      release-version: ${{ steps.set.outputs.release-version }}
    runs-on: ubuntu-latest
    steps:
    - id: set
      name: Set version
      run: |
        echo "::set-output name=release-version::v1.0.1023"

#  version:
#    if: startsWith(github.ref, 'refs/tags/')
#    needs: test
#    outputs:
#      release-version: ${{ steps.parse.outputs.version }}
#    runs-on: ubuntu-latest
#    steps:
#    - id: parse
#      env:
#        GITHUB_REF: ${{ github.ref }}
#      name: Parse version from tag ${{ github.ref }}
#      run: |
#        if [[ "${GITHUB_REF}" =~ ^refs/tags/(v[0-2]\.[0-9]+\.[0-9]+)$ ]]; then
#          echo "yup [${BASH_REMATCH[1]}]"
#          echo "::set-output name=release-version::${BASH_REMATCH[1]}"
#        else
#          echo nope
#        fi

  release:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RELEASE_DIR: .github-release
      RELEASE_VERSION: ${{ needs.version.outputs.release-version }}
    if: needs.version.outputs.release-version
    needs: version
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.14'
    - id: build
      name: Build release artifacts version ${{ env.RELEASE_VERSION }}
      run: |
        mkdir -p "${RELEASE_DIR}"
        for PLATFORM in windows linux darwin; do
          EXTENSION=""
          if [[ "${PLATFORM}" == 'windows' ]]; then
            EXTENSION=".exe"
          fi
          export GOOS="${PLATFORM}"
          export GOARCH=amd64
          export CGO_ENABLED=0

          OUT_FILE="${RELEASE_DIR}/clconf-${PLATFORM}${EXTENSION}"
          echo "Creating ${OUT_FILE} (${RELEASE_VERSION})"
          go build -ldflags "-X github.com/pastdev/clconf/v2/cmd.version=$RELEASE_VERSION" -o "${OUT_FILE}"

          echo "::set-output name=${PLATFORM}-artifact::${OUT_FILE}"
        done
        ls -lrt "${RELEASE_DIR}"
    - id: create-release
      name: Create release ${{ env.RELEASE_VERSION }}
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.RELEASE_VERSION }}
        release_name: ${{ env.RELEASE_VERSION }}
        draft: false
        prerelease: false
    - if: ${{ steps.build.outputs.darwin-artifact }}
      name: Upload darwin release ${{ env.RELEASE_VERSION }}
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ${{ steps.build.outputs.darwin-artifact }}
        asset_name: clconf-darwin
        asset_content_type: application/octet-stream
    - if: ${{ steps.build.outputs.linux-artifact }}
      name: Upload linux release ${{ env.RELEASE_VERSION }}
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ${{ steps.build.outputs.linux-artifact }}
        asset_name: clconf-linux
        asset_content_type: application/octet-stream
    - if: ${{ steps.build.outputs.windows-artifact }}
      name: Upload windows release ${{ env.RELEASE_VERSION }}
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ${{ steps.build.outputs.windows-artifact }}
        asset_name: clconf-windows.exe
        asset_content_type: application/octet-stream
