---
name: build

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.14'
    - run: go version
    - run: go test ./...

  release:
    if: startsWith( github.ref, 'refs/tags/releases/')
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Build release artifacts
      run: |
        for PLATFORM in windows linux darwin; do
          EXTENSION=""
          if [[ $PLATFORM = 'windows' ]]; then
            EXTENSION=".exe"
          fi
          export GOOS=$PLATFORM
          export GOARCH=amd64
          export CGO_ENABLED=0

          OUT_FILE="$GOPATH/bin/clconf-$PLATFORM$EXTENSION"
          echo "Creating $OUT_FILE ($TRAVIS_TAG)"
          go build -ldflags "-X github.com/pastdev/clconf/v2/cmd.version=$TRAVIS_TAG" -o $OUT_FILE
        done
        ls -lrt $GOPATH/bin
